export const authentification_constants = {
    LOGIN_REQUEST : 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS : 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILLURE : 'USERS_LOGIN_FAILURE',
    LOGOUT : 'USERS_LOGOUT'
}