export const authentification_constants = {
    LOGIN_REQUEST : 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS : 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILLURE : 'USERS_LOGIN_FAILURE',
    REGISTER_REQUEST : 'USERS_REGISTER',
    REGISTER_SUCCESS : 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILLURE : 'USERS_REGISTER_FAILLURE',
    LOGOUT : 'USERS_LOGOUT'
}